// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Group struct {
	ID         int64           `json:"id"`
	Balance    sql.NullFloat64 `json:"balance"`
	TelegramID int64           `json:"telegram_id"`
	Title      sql.NullString  `json:"title"`
	Url        sql.NullString  `json:"url"`
	CreatedAt  sql.NullTime    `json:"created_at"`
	UpdatedAt  sql.NullTime    `json:"updated_at"`
}

type User struct {
	ID                int64           `json:"id"`
	TelegramID        int64           `json:"telegram_id"`
	FirstName         string          `json:"first_name"`
	Username          sql.NullString  `json:"username"`
	BalanceGame       sql.NullFloat64 `json:"balance_game"`
	BalanceChats      sql.NullFloat64 `json:"balance_chats"`
	Status            string          `json:"status"`
	Language          string          `json:"language"`
	ReferFromID       sql.NullInt64   `json:"refer_from_id"`
	LastStreakClaimAt sql.NullTime    `json:"last_streak_claim_at"`
	CreatedAt         sql.NullTime    `json:"created_at"`
	UpdatedAt         sql.NullTime    `json:"updated_at"`
}

type UserGroup struct {
	ID              int64           `json:"id"`
	UserTelegramID  int64           `json:"user_telegram_id"`
	GroupTelegramID int64           `json:"group_telegram_id"`
	Balance         sql.NullFloat64 `json:"balance"`
}
